language: java
jdk:
  - oraclejdk8
script: mvn verify -P no-html-help
before_deploy:
  cp ./target/*.jar .
deploy:
  provider: releases
  prerelease: true
  api_key: "$token"
  file: "Thunder_STORM.jar"
  skip_cleanup: true
  on:
    tags: true
